apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: nginx-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-dyn
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
        storage: 1Gi


